name: Fetch Blogger Posts

on:
  schedule:
    - cron: '0 * * * *' # Har ghante chalega
  workflow_dispatch:

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run fetch_blogger_posts.js
        run: node fetch_blogger_posts.js
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add posts/
          git commit -m 'Update Blogger posts' || echo "No changes to commit"
          git push
